// Edit this file to add/update tools. Every page (homepage, comparison, review) pulls from here.
// affiliateLink: paste your tracking link once you're approved for each program.

export const tools = [
  {
    slug: "tool-one",
    name: "Tool One",
    tagline: "Placeholder tagline — replace with real positioning once you pick your program",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 }, // 0-100, fill in after your own review
    pros: ["Placeholder pro 1", "Placeholder pro 2", "Placeholder pro 3"],
    cons: ["Placeholder con 1", "Placeholder con 2"],
    affiliateLink: "#",
    rank: 1,
  },
  {
    slug: "tool-two",
    name: "Tool Two",
    tagline: "Placeholder tagline",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 },
    pros: ["Placeholder pro 1", "Placeholder pro 2"],
    cons: ["Placeholder con 1"],
    affiliateLink: "#",
    rank: 2,
  },
  {
    slug: "tool-three",
    name: "Tool Three",
    tagline: "Placeholder tagline",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 },
    pros: ["Placeholder pro 1", "Placeholder pro 2"],
    cons: ["Placeholder con 1"],
    affiliateLink: "#",
    rank: 3,
  },
  {
    slug: "tool-four",
    name: "Tool Four",
    tagline: "Placeholder tagline",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 },
    pros: ["Placeholder pro 1", "Placeholder pro 2"],
    cons: ["Placeholder con 1"],
    affiliateLink: "#",
    rank: 4,
  },
  {
    slug: "tool-five",
    name: "Tool Five",
    tagline: "Placeholder tagline",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 },
    pros: ["Placeholder pro 1", "Placeholder pro 2"],
    cons: ["Placeholder con 1"],
    affiliateLink: "#",
    rank: 5,
  },
  {
    slug: "tool-six",
    name: "Tool Six",
    tagline: "Placeholder tagline",
    price: "$—/mo",
    trustScore: { privacy: 0, features: 0, value: 0 },
    pros: ["Placeholder pro 1", "Placeholder pro 2"],
    cons: ["Placeholder con 1"],
    affiliateLink: "#",
    rank: 6,
  },
];
